# Generated by Django 3.0.4 on 2020-03-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0002_remove_alert_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='product_img',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
