# Generated by Django 3.0.4 on 2020-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0003_auto_20200314_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='product_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
