# Generated by Django 3.0.4 on 2020-03-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0004_alert_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
