# Generated by Django 3.0.4 on 2020-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0006_auto_20200315_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
