# Generated by Django 3.0.4 on 2020-03-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0007_auto_20200315_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='product_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
