# Generated by Django 3.0.4 on 2020-03-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0008_alert_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
