# Generated by Django 3.0.4 on 2020-03-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0011_userprofileinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user_Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
