# Generated by Django 3.0.4 on 2020-03-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0012_alert_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='user_Email',
        ),
    ]
